on:
  push:
    branches:
      - master
name: Main Workflow
jobs:
  Rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Push changes to stg
        run: |
          git checkout stg
          git rebase master
          git push -f
      - name: Push changes to prod
        run: |
          git checkout prod
          git rebase master
          git push -f